### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by ninsbl** [istSOS/istsos2#11]
Non-ascii characters in 'Service Provider' or 'Service identification' Metadata submitted through the admin Web-UI lead to Unicode Error:

'ascii' codec can't encode character u'\xf8' in position 1: ordinal not in range(128)

```
Status response: OK
Resource: waProvider
Method: PUT
Path /istsos/services/default/configsections/provider

```

**Comment by mantonovic** [comment]
Yes, something strange happens if using special characters in the admin interface.
Thanks for your comments. We will investigate this issue.

**Comment by mantonovic** [comment]
UnicodeEncodeError is really painful sometimes.
On my dev environment I've modified the istsos/application.py file forcing utf-8 enconding:

```
# ...
reload(sys)
sys.setdefaultencoding('utf-8')

def application(environ, start_response):
# ...
```
This fixed the issue when interacting with the web admin passing special characters.

**Comment by mantonovic** [comment]
testing special chars with istSOS looks ok..

![screenshot from 2017-01-12 14 30 02](https://cloud.githubusercontent.com/assets/1797931/21891652/04e8ee20-d8d4-11e6-8826-4f5983f31ad8.png)

Even with XML

![image](https://cloud.githubusercontent.com/assets/1797931/21891682/2b00990a-d8d4-11e6-8a90-81601d4b4a66.png)

**Comment by ninsbl** [comment]
Thanks!
