### ISSUE TITLE
Axis order handling

### ISSUE THREAD

**Issue by m431m** [istSOS/istsos2#12]
Hi,

Coordinates in SensorML document are in XY axis order with EPSG:4326 code, and not in YX order.
Is there a reason for that ?

I also wonder about the relevance of Z axis with standard. Is Z axis strictly mandatory in IstSOS ?

```
<sml:location>
    <gml1:Point srsName="EPSG:4326" gml1:id="foo">
        <gml1:coordinates>5.1,42.1,0</gml1:coordinates>
    </gml1:Point>
</sml:location>
````

m431m

**Comment by mantonovic** [comment]
Hi m431m,
Thanks for reporting this..
I will check this before next version will be released.

**Comment by mantonovic** [comment]
That's the normal behaviour when representing point with gml.

In fact Postgis consider XYZ the order of the coordinates:

```
SELECT 
	st_x(ST_GeomFromGML('<gml1:Point srsName="EPSG:4326" gml1:id="foo"><gml1:coordinates>5.1,42.1,0</gml1:coordinates></gml1:Point>')),
	st_y(ST_GeomFromGML('<gml1:Point srsName="EPSG:4326" gml1:id="foo"><gml1:coordinates>5.1,42.1,0</gml1:coordinates></gml1:Point>')),
	st_z(ST_GeomFromGML('<gml1:Point srsName="EPSG:4326" gml1:id="foo"><gml1:coordinates>5.1,42.1,0</gml1:coordinates></gml1:Point>'));
```
Result: 
```
st_x;st_y;st_z
5.1;42.1;0
```

**Comment by m431m** [comment]
Hi,

Another point for consideration (PostGIS may be wrong).

If I understand correctly the OGC schema, in SensorML version 1.0.1: GML should be done in version 3.1.1 (http://schemas.opengis.net/sensorML/1.0.1/system.xsd)

And in GML 3.1.1, 'coordinates' and 'coord' elements are deprecated. 'pos' element should be used first (http://schemas.opengis.net/gml/3.1.1/base/geometryBasic0d1d.xsd):

```
<element name="Point" type="gml:PointType" substitutionGroup="gml:_GeometricPrimitive"/>
<complexType name="PointType">
    <annotation>
        <documentation>A Point is defined by a single coordinate tuple.</documentation>
    </annotation>
    <complexContent>
        <extension base="gml:AbstractGeometricPrimitiveType">
            <sequence>
                <choice>
                    <annotation>
                        <documentation>GML supports two different ways to specify the direct poisiton of a point. 1. The "pos" element is of type DirectPositionType.</documentation>
                    </annotation>
                    <element ref="gml:pos"/>
                    <element ref="gml:coordinates">
                        <annotation>
                            <documentation>Deprecated with GML version 3.1.0 for coordinates with ordinate values that are numbers. Use "pos" instead. The "coordinates" element shall only be used for coordinates with ordinates that require a string representation, e.g. DMS representations.</documentation>
                        </annotation>
                    </element>
                    <element ref="gml:coord">
                        <annotation>
                                <documentation>Deprecated with GML version 3.0. Use "pos" instead. The "coord" element is included for backwards compatibility with GML 2.</documentation>
                        </annotation>
                    </element>
                </choice>
            </sequence>
        </extension>
    </complexContent>
</complexType>
```


So, I guess this following should be more proper:

```
<sml:location>
    <gml:Point srsName="EPSG:4326" gml:id="foo">
        <gml:pos>42.1,5.1</gml:pos>
    </gml:Point>
</sml:location>
```

Then, the coordinate tuple should be following (have to follow :p in ) CRS definition.
But EPSG:4326 does not define Z axis, am I wrong ?

m431m

m431m

**Comment by m431m** [comment]
http://postgis.net/docs/ST_AsGML.html

> Return the geometry as a Geography Markup Language (GML) element. The version parameter, if specified, may be either 2 or 3. If no version parameter is specified then the default is assumed to be 2.

> GML 2 refer to 2.1.2 version, GML 3 to 3.1.1 version

> The 'options' argument is a bitfield. It could be used to define CRS output type in GML output, and to declare data as lat/lon: 
> ...
> * 16: Declare that datas are lat/lon (e.g srid=4326). Default is to assume that data are planars. This option is useful for GML 3.1.1 output only, related to axis order. So if you set it, it will swap the coordinates so order is lat lon instead of database lon lat.

**Comment by m431m** [comment]
#https://github.com/m431m/istsos2/commit/60ec94d7701e709b3ebe2564bf363f58fb578525 #
