### ISSUE TITLE
DescribeSensor: InvalidParameterValue for outputFormat

### ISSUE THREAD

**Issue by ninsbl** [istSOS/istsos2#23]
DescribeSensor request yields in exception:

http://istsos.org/istsos/demo?request=DescribeSensor&procedure=GARBOW&service=SOS&version=1.0.0&outputFormat=text/xml;subtype=%22sensorML/1.0.1%22

```
<Exception locator="outputFormat" exceptionCode="InvalidParameterValue">
<ExceptionText>
Supported "outputFormat" values are: text/xml;subtype="sensorML/1.0.1"
</ExceptionText>
</Exception>
</ExceptionReport>

```

See also this possibly related issue in java-core:
https://github.com/istSOS/java-core/issues/3

**Comment by ninsbl** [comment]
This POST request however seems to work:

```
<?xml version="1.0" encoding="UTF-8"?>
    <sos:describeSensor
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://schemas.opengis.net/sos/1.0.0/sosAll.xsd"
       xmlns:sos="http://www.opengis.net/sos/1.0"
       xmlns:gml="http://www.opengis.net/gml/3.2"
       xmlns:ogc="http://www.opengis.net/ogc"
       xmlns:om="http://www.opengis.net/om/1.0"
       service="SOS"
       outputFormat='text/xml;subtype="sensorML/1.0.1"'>

          <procedure>T_LUGANO</procedure>
    </sos:describeSensor>

```

**Comment by nuest** [comment]
Not sure about the standards requirements here (didn't check), but URL-encoding the value of `outputFormat` does not help either (I'm pretty sure the latter one is how it is supposed to be):

http://istsos.org/istsos/demo?request=DescribeSensor&procedure=GARBOW&service=SOS&version=1.0.0&outputFormat=text/xml;subtype%3D%22sensorML/1.0.1%22

http://istsos.org/istsos/demo?request=DescribeSensor&procedure=GARBOW&service=SOS&version=1.0.0&outputFormat=text/xml;subtype%3D"sensorML/1.0.1"

**Comment by massimiliano-cannata** [comment]
I agree, but I think to remember we had to modify to pass cite test..

Need to check though...

Il 06 set 2017 10:39 AM, "Daniel Nüst" <notifications@github.com> ha
scritto:

**Comment by mantonovic** [comment]
Hi the correct request is this one:

http://istsos.org/istsos/demo?request=DescribeSensor&procedure=GRABOW&service=SOS&version=1.0.0&outputFormat=text%2Fxml%3Bsubtype%3D%22sensorML%2F1.0.1%22

It does now worked beacouse of the procedure name that is misspelled: GARBOW instead of GRABOW

**Comment by ninsbl** [comment]
Yes, thanks, Milan!

However, it seems to be also an issue of how the request is formated. As this:

http://istsos.org/istsos/demo?request=DescribeSensor&procedure=GRABOW&service=SOS&version=1.0.0&outputFormat=text/xml;subtype="sensorML/1.0.1"

(with correct naming of the procedure) does not work.
Also the exception would be misleading if the issue only was a typo in the procedure name... Would`nt it?

**Comment by mantonovic** [comment]
I agree with you about the misleading message, we should change that message.

Parameter encoding is mandatory, text/xml;subtype="sensorML/1.0.1" contains some reserved characters (in our case: "/"  ";" "="). As you can see in the IETF Standard of Uniform Resource Identifier (URI): Generic Syntax.

That's why we have to send: text%2Fxml%3Bsubtype%3D"sensorML%2F1.0.1" instead of the more readable representation.

_PS: the double quotes are not encoded, that's because they are not reserved._

**Comment by ninsbl** [comment]
Thanks Milan for the explanation!
So this is not an istSOS problem and we can close the issue, right!?
If not please reopen!
