### ISSUE TITLE
insertObservation using interface

### ISSUE THREAD

**Issue by massimiliano-cannata** [istSOS/istsos2#6]
when use the data editor in the webAdmin interface, submitted data value and qualityIndex columns are inverted, resulting in inserting values as QI and QI as values

Example: 
data=18°C, QI=100 result after insertion in data=100°C, QI=18

Here the example of incorrect JSON request to walib:
`{"AssignedSensorId":"9c2e54345cbdc00e1c5c8d19ac812930","ForceInsert":"true","Observation":{"name":"LOCARNO","samplingTime":{"duration":"P513DT10H50M","beginPosition":"2015-10-26T23:00:00Z","endPosition":"2015-10-28T23:00:00Z"},"result":{"DataArray":{"elementCount":"3","values":[["2015-10-26T23:00:00Z","0","200","200","0"],["2015-10-27T23:00:00Z","18.2","200","200","0"],["2015-10-28T23:00:00Z","2","200","200","0"]],"field":[{"definition":"urn:ogc:def:parameter:x-istsos:1.0:time:iso8601","name":"Time"},{"definition":"urn:ogc:def:parameter:x-istsos:1.0:meteo:air:rainfall","name":"air-rainfall","uom":"mm"},{"definition":"urn:ogc:def:parameter:x-istsos:1.0:meteo:air:rainfall:qualityIndex","name":"air-rainfall:qualityIndex","uom":"-"},{"definition":"urn:ogc:def:parameter:x-istsos:1.0:meteo:air:temperature","name":"air-temperature","uom":"\u00b0C"},{"definition":"urn:ogc:def:parameter:x-istsos:1.0:meteo:air:temperature:qualityIndex","name":"air-temperature:qualityIndex","uom":"-"}]}},"featureOfInterest":{"geom":"<gml:Point srsName='EPSG:4326'><gml:coordinates>8.792120000000001,46.155149999999999,197.800000000000011</gml:coordinates></gml:Point>","name":"urn:ogc:def:feature:x-istsos:1.0:Point:LOCARNO"},"observedProperty":{"component":["urn:ogc:def:parameter:x-istsos:1.0:time:iso8601","urn:ogc:def:parameter:x-istsos:1.0:meteo:air:rainfall","urn:ogc:def:parameter:x-istsos:1.0:meteo:air:rainfall:qualityIndex","urn:ogc:def:parameter:x-istsos:1.0:meteo:air:temperature","urn:ogc:def:parameter:x-istsos:1.0:meteo:air:temperature:qualityIndex"],"CompositePhenomenon":{"dimension":"5","id":"comp_3","name":"timeSeriesOfObservations"}},"procedure":"urn:ogc:def:procedure:x-istsos:1.0:LOCARNO"}}`

**Comment by mantonovic** [comment]
Cannot replicate error.
Temporary suspended.
